### ISSUE TITLE
Add README case: get transaction receipt json from a transaction hash

### ISSUE THREAD

**Issue by biboran** [zeriontech/Web3Swift#130]
We can make a couple cases here:
1. Fetching json from a known transaction hash
2. Fetching json by hashing a transaction
3. Fetching json from a transaction hash as a chain of objects that represent a transaction hash returned by the `SendRawTransactionProcedure`

**Comment by rockfridrich** [comment]
@biboran I think that fetching JSON by hash is enough. We could print `hash` in sending transaction example
