### ISSUE TITLE
Add README case: abi response interpretation from a contract call

### ISSUE THREAD

**Issue by biboran** [zeriontech/Web3Swift#132]
Lets add an example detailing how one can use `EthContractCall` and abi decoding functionality.

**Comment by rockfridrich** [comment]
@biboran I have mentioned decoding in #150. However, it was a simple example that does not involve ABI decoding. What contract should we use for a demo? Perhaps we can use [CryptoKitties contract](https://etherscan.io/address/0x06012c8cf97bead5deae237070f9587f8e7a266d#readContract). 
It has got several returning types including tuple.
