### ISSUE TITLE
Missing Ethereum specific message signing

### ISSUE THREAD

**Issue by rockfridrich** [zeriontech/Web3Swift#149]
We need to implement Ethereum specific message signing. 
Here is a link to the description — [link](https://medium.com/@angellopozo/ethereum-signing-and-validating-13a2d7cb0ee3).
Here is an Etherscan page that checks signed message — [link](https://etherscan.io/verifySig)

We could implement `EthereumSignedMessageBytes` as an object for getting signed message

**Comment by 0crat** [comment]
@rockfridrich[/z](https://www.0crat.com/u/rockfridrich) I'm not managing this repo, remove the [webhook](https://github.com/zeriontech/Web3Swift/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `zeriontech/web3swift` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `zeriontech/web3swift` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by rockfridrich** [comment]
@kondranton let's create signing first
