### ISSUE TITLE
TrimmedPrefixString is inconsistent with TrimmedPrefixBytes

### ISSUE THREAD

**Issue by biboran** [zeriontech/Web3Swift#152]
`TrimmedPrefixString` only drops the first encounter of the prefix while `TrimmedPrefixBytes` drops every leading element specified element.

**Comment by rockfridrich** [comment]
What is the expected behavior?

**Comment by biboran** [comment]
@rockfridrich let's make `TrimmedPrefixString` behave the same way `TrimmedPrefixBytes` does which is:

1. Drop leading element until it's equal to specified prefix
2. Last element is not considered leading

**Comment by biboran** [comment]
@rockfridrich let me give you test cases instead:

Trim «0x»:
0x0x1234 -> 1234
0x0x0x  -> 0x
0x0x0x0 -> 0
abc -> abc
