### ISSUE TITLE
Missing Decimal and Normalized Decimal conversion 

### ISSUE THREAD

**Issue by rockfridrich** [zeriontech/Web3Swift#213]
In most of the cases with tokens, you need to deal with `Decimal` in your application. 
There are two major use cases for it: 
1) A `Decimal` that is stored somewhere in the memory of an application
2) A normalized `Decimal` that is divided by 10 ^ power to represent a meaningful number.

Let's add two classes to allow easier conversion from `EthNumber`:
1) `DecimalFromHex(hex: BytesScalar)`
2) `NormalizedDecimalFromHex(hex:BytesScalar, power: Int)`

**Comment by timofeys1** [comment]
I am not sure I understand what those instances would represent. Could you please give an example of some unit tests you would expect those classes to pass?

**Comment by rockfridrich** [comment]
@biboran basically, we need to allow a super easy and convenient way for converting EthNumber to Decimal. And then for cases when Decimal required to be divided by 10 ^ power. This is a super common everyday task when you deal with numbers in Ethereum. We already allow getting a decimal string quickly.
