### ISSUE TITLE
InvalidTypeError is not a DescribedError

### ISSUE THREAD

**Issue by timofeys1** [zeriontech/Web3Swift#73]
`InvalidTypeError` should tell which type was expected and which was retrieved from `JSON`

**Comment by 0crat** [comment]
The job [#73](https://github.com/blockstoreapp/web3swift/issues/73) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 points just awarded to @biboran[/z](https://www.0crat.com/u/biboran)
