### ISSUE TITLE
Extraneous, missing, and incorrect interfaces

### ISSUE THREAD

**Issue by timofeys1** [zeriontech/Web3Swift#81]
A lot of our current interfaces duplicate each other unnecessarily and violate laziness: 
* `Hex` in its current form is not a good design. What we want most of the time is actually a declarative interface for passing bytes dependencies around. I don't see a better way to refactor it but to use `StringScalar` for working with strings (Address), a `NumberScalar` for working with numbers (ECSignature, GasPrice, GasEstimate) instead of `Hex`. 
* A lot of our interfaces do not provide any real services but simply serve as typealiases for `Hex` and disambiguate their intention by their interface. I don't think this is good. Most of them should be `NumberScalar` or `StringScalar`.

**Comment by 0crat** [comment]
The job [#81](https://github.com/blockstoreapp/web3swift/issues/81) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 points just awarded to @biboran[/z](https://www.0crat.com/u/biboran)
